<!-- Generate Section Rules List -->

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<h4 class="text text-color">Section Definitions and Rules</h4>
		
		<!-- Generate list of TABS -->
		<ul class="nav nav-pills">
		<?php
            // Use sectionList generated by op/get_contest.php
            $first = true;
            foreach ($contestSectionList AS $tmp_section => $tmp_details) {
                $sectionName = str_nosep($tmp_section);
		?>
			<li <?php echo $first ? "class='active'" : ""; ?>  ><a data-toggle="pill" href="#section_<?=$sectionName;?>" ><?=$tmp_section;?></a></li>
		<?php
				$first = false;
			}
		?>
		</ul>

		<!-- Generate TAB Contents -->
		<div class="tab-content">
		<?php
			$first = true;
            foreach ($contestSectionList AS $tmp_section => $tmp_details) {
				$sectionName = str_nosep($tmp_section);
		?>
			<div id="section_<?=$sectionName;?>" class="tab-pane fade <?php echo $first ? 'in active' : '';?> " >
				<h5 class="text text-color">Maximum Pictures per Entry : <?=$tmp_details['max_pics_per_entry'];?></h5>
		<?php
				if ($tmp_details['rules_blob'] == "") {
		?>
                <h5 class="text text-color">Definition</h5>
                <?=$tmp_details['description'];?>
                <h5 class="text text-color">Rules</h5>
                <?=$tmp_details['rules'];?>
		<?php
				}
				else {
		?>
				<div class="row">
					<div class="col-sm-12">
						<?= file_get_contents("salons/$contest_yearmonth/blob/" . $tmp_details['rules_blob']);?>
					</div>
				</div>
		<?php
				}
				$first = false;
		?>
			</div>
		<?php
			}  //for each in sectionList
		?>
		</div>  <!-- tab-content -->
	</div> <!-- col -->
</div>  <!-- row -->

